// 2D procedural art for districts, shops, and dialog portraits: creatures, buildings, skies, ground, icons.
import { getSpecies } from '../data/species.js';
import { makeRng, hashStr, shade, mix, rgba, hsl, clamp, lerp } from '../util.js';

export function rr(ctx, x, y, w, h, r) { r = Math.min(r, w / 2, h / 2); ctx.beginPath(); ctx.moveTo(x + r, y); ctx.arcTo(x + w, y, x + w, y + h, r); ctx.arcTo(x + w, y + h, x, y + h, r); ctx.arcTo(x, y + h, x, y, r); ctx.arcTo(x, y, x + w, y, r); ctx.closePath(); }
export function label(ctx, text, x, y, size, color = '#fff', stroke = '#141a2e', align = 'center', font = '"Arial Rounded MT Bold", "Trebuchet MS", sans-serif') {
  ctx.font = `bold ${size}px ${font}`; ctx.textAlign = align; ctx.textBaseline = 'middle'; ctx.lineJoin = 'round'; ctx.lineWidth = Math.max(2, size * 0.16); ctx.strokeStyle = stroke; ctx.strokeText(text, x, y); ctx.fillStyle = color; ctx.fillText(text, x, y);
}
const circle = (ctx, x, y, r, fill, stroke, lw = 3) => { ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2); if (fill) { ctx.fillStyle = fill; ctx.fill(); } if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = lw; ctx.stroke(); } };
const ellipse = (ctx, x, y, rx, ry, fill, stroke, lw = 3, rot = 0) => { ctx.beginPath(); ctx.ellipse(x, y, rx, ry, rot, 0, Math.PI * 2); if (fill) { ctx.fillStyle = fill; ctx.fill(); } if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = lw; ctx.stroke(); } };
const INK = '#141a2e';

// ---------- creatures (2D shopkeepers & portraits) ----------
// opts: x, y (feet), s (scale, 1 = ~220px tall), skin, team colors, accessory, talk (0..1 mouth open), blink (bool), look ({x,y} -1..1), headOnly
export function drawCreature(ctx, speciesId, o = {}) {
  const sp = getSpecies(speciesId); const s = o.s || 1; const x = o.x || 0, y = o.y || 0;
  const skin = o.skin || sp.skin[o.skinIndex || 0]; const acc = sp.accent || '#ff9bb0'; const shirt = o.shirt || (o.colors ? o.colors[0] : '#4a6fd6'); const shirt2 = o.colors ? o.colors[1] : '#ffffff';
  ctx.save(); ctx.translate(x, y); ctx.scale(s, s); ctx.lineJoin = 'round'; ctx.lineCap = 'round';
  const hs = sp.head.scale; const hr = 52 * Math.max(hs[0], 1) ; const hw = hr * hs[0], hh = hr * hs[1] * ({ egg: 1.2, wide: 0.9, flat: 0.78 }[sp.head.shape] || 1) * (sp.head.shape === 'wide' ? 1 : 1);
  const bodyW = sp.body.shape === 'round' || sp.body.shape === 'blob' ? 78 : sp.body.shape === 'box' ? 72 : 62; const bodyH = 78;
  const bob = o.bob || 0; ctx.translate(0, -bob);
  const headY = -bodyH - hh * 0.85 - 14; // head center
  if (!o.headOnly) {
    // legs
    if (sp.body.shape !== 'wisp') for (const sd of [-1, 1]) { ctx.fillStyle = shade(shirt2, -0.1); rr(ctx, sd * 16 - 11, -34, 22, 34, 9); ctx.fill(); ctx.strokeStyle = INK; ctx.lineWidth = 3; ctx.stroke(); ctx.fillStyle = sp.features.includes('feet:orange') ? '#ffb84d' : '#23233a'; rr(ctx, sd * 16 - 15, -10, 30, 12, 5); ctx.fill(); ctx.stroke(); }
    else { ctx.fillStyle = skin; ctx.beginPath(); ctx.moveTo(-bodyW / 2, -bodyH * 0.5); ctx.quadraticCurveTo(-10, -5, 0, 0); ctx.quadraticCurveTo(10, -5, bodyW / 2, -bodyH * 0.5); ctx.closePath(); ctx.fill(); ctx.strokeStyle = INK; ctx.lineWidth = 3; ctx.stroke(); }
    // body
    ctx.fillStyle = shirt; ctx.strokeStyle = INK; ctx.lineWidth = 3.5;
    if (sp.body.shape === 'round' || sp.body.shape === 'blob') { ellipse(ctx, 0, -bodyH / 2 - 8, bodyW / 2, bodyH / 2 + 6, shirt, INK, 3.5); }
    else if (sp.body.shape === 'box') { rr(ctx, -bodyW / 2, -bodyH - 8, bodyW, bodyH + 6, 8); ctx.fill(); ctx.stroke(); }
    else { rr(ctx, -bodyW / 2, -bodyH - 8, bodyW, bodyH + 6, 24); ctx.fill(); ctx.stroke(); }
    if (sp.features.includes('stripes')) for (let i = 0; i < 3; i++) { ctx.fillStyle = acc; rr(ctx, -bodyW / 2 + 4, -bodyH + 6 + i * 22, bodyW - 8, 9, 4); ctx.fill(); }
    if (sp.features.includes('belly')) { ellipse(ctx, 0, -bodyH / 2, bodyW * 0.3, bodyH * 0.36, sp.belly || '#f4f4f4', null); }
    // accessory on body
    if (o.accessory === 'apron') { ctx.fillStyle = '#fff6e6'; rr(ctx, -bodyW / 2 + 8, -bodyH + 4, bodyW - 16, bodyH - 4, 10); ctx.fill(); ctx.stroke(); ctx.strokeStyle = '#d9534f'; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(-14, -bodyH + 4); ctx.lineTo(-4, -bodyH - 6); ctx.moveTo(14, -bodyH + 4); ctx.lineTo(4, -bodyH - 6); ctx.stroke(); }
    if (o.accessory === 'coach') { ctx.fillStyle = '#ffffff'; rr(ctx, -bodyW / 2 + 2, -bodyH - 8, bodyW - 4, 24, 8); ctx.fill(); ctx.strokeStyle = INK; ctx.stroke(); ctx.fillStyle = INK; ctx.fillRect(-14, -bodyH + 8, 28, 16); ctx.fillStyle = '#fff'; rr(ctx, -12, -bodyH + 10, 24, 12, 2); ctx.fill(); for (let i = 0; i < 3; i++) { ctx.strokeStyle = '#4a6fd6'; ctx.lineWidth = 1.5; ctx.beginPath(); ctx.moveTo(-9, -bodyH + 13 + i * 3); ctx.lineTo(9, -bodyH + 13 + i * 3); ctx.stroke(); } }
    if (o.accessory === 'gear') { ctx.strokeStyle = '#ffd23f'; ctx.lineWidth = 4; ctx.beginPath(); ctx.moveTo(-bodyW / 2 + 6, -bodyH + 10); ctx.lineTo(bodyW / 2 - 6, -bodyH + 40); ctx.stroke(); }
    // arms
    for (const sd of [-1, 1]) { ctx.strokeStyle = INK; ctx.lineWidth = 3.5; ctx.fillStyle = shirt2; const ax = sd * (bodyW / 2 + 2); const wave = o.wave && sd > 0 ? -50 : 0; rr(ctx, ax - 10, -bodyH + 6 + wave * 0.6, 20, 44, 9); ctx.fill(); ctx.stroke(); circle(ctx, ax, -bodyH + 52 + wave, sp.features.includes('pincers') ? 16 : 12, skin, INK, 3); }
  }
  // neck/head
  const hy = o.headOnly ? 0 : headY; const hx = 0;
  const headShape = () => { if (sp.head.shape === 'box') rr(ctx, hx - hw, hy - hh, hw * 2, hh * 2, 10); else if (sp.head.shape === 'gem') { ctx.beginPath(); for (let i = 0; i < 6; i++) { const a = i / 6 * Math.PI * 2 - Math.PI / 2; ctx.lineTo(hx + Math.cos(a) * hw * 1.05, hy + Math.sin(a) * hh * 1.05); } ctx.closePath(); } else { ctx.beginPath(); ctx.ellipse(hx, hy, hw, hh, 0, 0, Math.PI * 2); } };
  // behind-head features
  if (sp.features.includes('ears:long')) for (const sd of [-1, 1]) { ctx.fillStyle = skin; rr(ctx, hx + sd * 22 - 12, hy - hh - 70, 24, 78, 12); ctx.fill(); ctx.strokeStyle = INK; ctx.lineWidth = 3; ctx.stroke(); ctx.fillStyle = acc; rr(ctx, hx + sd * 22 - 6, hy - hh - 60, 12, 58, 6); ctx.fill(); }
  if (sp.features.includes('ears:round')) for (const sd of [-1, 1]) { circle(ctx, hx + sd * hw * 0.85, hy - hh * 0.7, 22, skin, INK); circle(ctx, hx + sd * hw * 0.85, hy - hh * 0.7, 13, acc, null); }
  if (sp.features.includes('ears:pointy')) for (const sd of [-1, 1]) { ctx.fillStyle = skin; ctx.beginPath(); ctx.moveTo(hx + sd * hw * 0.4, hy - hh * 0.7); ctx.lineTo(hx + sd * hw * 0.95, hy - hh - 30); ctx.lineTo(hx + sd * hw * 1.0, hy - hh * 0.3); ctx.closePath(); ctx.fill(); ctx.strokeStyle = INK; ctx.lineWidth = 3; ctx.stroke(); }
  if (sp.features.includes('ears:floppy')) for (const sd of [-1, 1]) { ctx.fillStyle = skin; rr(ctx, hx + sd * hw - 12, hy - hh * 0.4, 24, 60, 12); ctx.fill(); ctx.strokeStyle = INK; ctx.lineWidth = 3; ctx.stroke(); }
  const ant = sp.features.find(f => f.startsWith('antenna:')); if (ant) { const n = +ant.split(':')[1]; for (let i = 0; i < n; i++) { const ax = n === 1 ? 0 : (i ? 18 : -18); ctx.strokeStyle = INK; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(hx + ax, hy - hh + 4); ctx.lineTo(hx + ax * 1.6, hy - hh - 34); ctx.stroke(); circle(ctx, hx + ax * 1.6, hy - hh - 38, 7, acc, INK); } }
  if (sp.features.includes('afro')) circle(ctx, hx, hy - hh * 0.3, hw * 1.45, '#1a1a1a', INK, 3);
  if (sp.features.includes('cap')) { ctx.fillStyle = o.colors ? o.colors[0] : acc; ctx.beginPath(); ctx.ellipse(hx, hy - hh * 0.55, hw * 1.7, hh * 0.9, 0, Math.PI, Math.PI * 2); ctx.closePath(); ctx.fill(); ctx.strokeStyle = INK; ctx.lineWidth = 3; ctx.stroke(); for (let i = 0; i < 5; i++) circle(ctx, hx + (i - 2) * hw * 0.6, hy - hh * 0.75 - Math.abs(i - 2) * -6 - 14, 8, '#fff3e6', null); }
  if (sp.features.includes('flame')) for (let i = -1; i <= 1; i++) { ctx.fillStyle = i ? '#ffb347' : '#ffe14d'; ctx.beginPath(); ctx.moveTo(hx + i * 16 - 10, hy - hh + 6); ctx.quadraticCurveTo(hx + i * 16 + (o.t ? Math.sin(o.t * 12 + i) * 6 : 0), hy - hh - 40 - (i ? 0 : 14), hx + i * 16 + 10, hy - hh + 6); ctx.fill(); }
  if (sp.features.includes('crest') || sp.features.includes('tufts')) for (let i = -1; i <= 1; i += (sp.features.includes('tufts') ? 2 : 1)) { ctx.fillStyle = acc; ctx.beginPath(); ctx.moveTo(hx + i * 14 - 8, hy - hh + 8); ctx.lineTo(hx + i * 22, hy - hh - 30); ctx.lineTo(hx + i * 14 + 8, hy - hh + 8); ctx.fill(); ctx.strokeStyle = INK; ctx.lineWidth = 2.5; ctx.stroke(); }
  if (sp.features.includes('halo')) { ellipse(ctx, hx, hy - hh - 22, hw * 0.8, 9, null, acc, 5); }
  if (sp.features.includes('spikes')) for (let i = 0; i < 3; i++) { ctx.fillStyle = acc; ctx.beginPath(); ctx.moveTo(hx - 10 + i * 10, hy - hh + 4); ctx.lineTo(hx - 4 + i * 10, hy - hh - 22 + i * 4); ctx.lineTo(hx + 2 + i * 10, hy - hh + 4); ctx.fill(); }
  if (sp.features.includes('flower')) { circle(ctx, hx, hy - hh - 10, 12, '#ffe66d', INK); for (let i = 0; i < 6; i++) { const a = i / 6 * Math.PI * 2; circle(ctx, hx + Math.cos(a) * 18, hy - hh - 10 + Math.sin(a) * 18, 9, acc, INK, 2); } }
  if (sp.features.includes('leaves')) for (const sd of [-1, 1]) { ctx.fillStyle = '#3f9b3f'; ellipse(ctx, hx + sd * hw * 0.95, hy - hh * 0.2, 22, 10, '#3f9b3f', INK, 2.5, sd * 0.6); }
  if (sp.features.includes('gear')) { ctx.fillStyle = '#8a919c'; for (let i = 0; i < 8; i++) { const a = i / 8 * Math.PI * 2; ctx.fillRect(hx + hw * 0.6 + Math.cos(a) * 16 - 4, hy - hh - 10 + Math.sin(a) * 16 - 4, 8, 8); } circle(ctx, hx + hw * 0.6, hy - hh - 10, 13, '#8a919c', INK); circle(ctx, hx + hw * 0.6, hy - hh - 10, 5, '#3a3a44', null); }
  if (sp.features.includes('key')) { ctx.strokeStyle = '#8a6a1a'; ctx.lineWidth = 5; ctx.beginPath(); ctx.moveTo(hx + hw * 0.9, hy - hh * 0.6); ctx.lineTo(hx + hw * 0.9 + 22, hy - hh * 0.6 - 24); ctx.stroke(); ellipse(ctx, hx + hw * 0.9 + 26, hy - hh * 0.6 - 30, 9, 9, null, '#8a6a1a', 5); }
  // head
  ctx.fillStyle = skin; headShape(); ctx.fill(); ctx.strokeStyle = INK; ctx.lineWidth = 3.5; ctx.stroke();
  if (sp.features.includes('mask')) { ctx.fillStyle = '#1a1a24'; rr(ctx, hx - hw * 0.9, hy - 14, hw * 1.8, 30, 12); ctx.fill(); }
  if (sp.features.includes('bubblehelm')) { ctx.strokeStyle = 'rgba(200,240,255,0.9)'; ctx.lineWidth = 4; ctx.beginPath(); ctx.ellipse(hx, hy, hw * 1.35, hh * 1.3, 0, 0, Math.PI * 2); ctx.stroke(); ctx.fillStyle = 'rgba(200,240,255,0.15)'; ctx.fill(); }
  if (sp.features.includes('bandana')) { ctx.fillStyle = o.colors ? o.colors[0] : '#e63946'; ctx.beginPath(); ctx.ellipse(hx, hy - hh * 0.6, hw * 1.02, hh * 0.45, 0, Math.PI, Math.PI * 2); ctx.fill(); ctx.strokeStyle = INK; ctx.lineWidth = 3; ctx.stroke(); }
  // eyes
  const e = sp.eyes; const eyeY = hy + hh * -0.05; const esz = 11 * (e.size || 1); const lookX = (o.look ? o.look.x : 0) * 4, lookY = (o.look ? o.look.y : 0) * 3;
  const eyePos = e.count === 1 ? [[0, 0]] : e.count === 3 ? [[-hw * 0.42, 0], [hw * 0.42, 0], [0, -hh * 0.45]] : e.count === 4 ? [[-hw * 0.35, 0], [hw * 0.35, 0], [-hw * 0.6, -hh * 0.35], [hw * 0.6, -hh * 0.35]] : e.count === 0 ? [] : [[-hw * 0.4, 0], [hw * 0.4, 0]];
  if (e.style === 'visor') { ctx.fillStyle = e.color || '#3ee8ff'; rr(ctx, hx - hw * 0.85, eyeY - 10, hw * 1.7, 20, 8); ctx.fill(); ctx.shadowColor = e.color || '#3ee8ff'; }
  if (e.style === 'clock') { circle(ctx, hx, hy, hw * 0.75, '#fff8dc', INK, 3); ctx.strokeStyle = INK; ctx.lineWidth = 4; ctx.beginPath(); ctx.moveTo(hx, hy); ctx.lineTo(hx, hy - hh * 0.5); ctx.moveTo(hx, hy); ctx.lineTo(hx + hw * 0.4, hy + 6); ctx.stroke(); }
  for (const [ex, ey] of eyePos) {
    const px = hx + ex, py = eyeY + ey; const small = eyePos.length > 2 && ey !== 0 ? 0.7 : 1; const r = esz * small;
    if (o.blink && e.style !== 'black' && e.style !== 'glow') { ctx.strokeStyle = INK; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(px - r, py); ctx.lineTo(px + r, py); ctx.stroke(); continue; }
    if (e.style === 'black') { ellipse(ctx, px, py, r * 1.25, r * (e.size > 1.4 ? 1.9 : 1.4), '#0a0a12', null, 0, ex > 0 ? -0.3 : 0.3); circle(ctx, px - r * 0.35, py - r * 0.5, r * 0.3, '#fff', null); }
    else if (e.style === 'glow') { circle(ctx, px, py, r, e.color || '#fff', INK, 2); if (e.pupil) circle(ctx, px + lookX * 0.5, py + lookY * 0.5, r * 0.45, e.pupil, null); }
    else if (e.style === 'dot') circle(ctx, px, py, r * 0.5, INK, null);
    else if (e.style === 'hollow') ellipse(ctx, px, py, r * 1.1, r * 1.4, '#1a1030', null);
    else { ellipse(ctx, px, py, r, r * 1.2, e.color && e.style === 'normal' ? e.color : '#ffffff', INK, 2.5); circle(ctx, px + lookX, py + lookY, r * 0.55, e.pupil || '#101018', null); circle(ctx, px + lookX + r * 0.2, py + lookY - r * 0.3, r * 0.2, '#fff', null); }
  }
  if (sp.features.includes('shades')) { ctx.fillStyle = '#111118'; rr(ctx, hx - hw * 0.85, eyeY - 12, hw * 1.7, 22, 6); ctx.fill(); ctx.strokeStyle = INK; ctx.stroke(); }
  if (sp.features.includes('monocle')) { circle(ctx, hx + hw * 0.4, eyeY, esz * 1.5, null, '#ffd700', 3); }
  if (sp.features.includes('eyepatch')) { circle(ctx, hx + hw * 0.4, eyeY, esz * 1.3, '#111118', null); ctx.strokeStyle = '#111118'; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(hx + hw * 0.4 - esz, eyeY - 6); ctx.lineTo(hx - hw, hy - hh * 0.4); ctx.stroke(); }
  if (sp.features.includes('visor:cyber')) { ctx.fillStyle = 'rgba(43,240,255,0.7)'; rr(ctx, hx - hw * 0.9, eyeY - 22, hw * 1.8, 12, 5); ctx.fill(); }
  // nose / mouth
  const my = hy + hh * 0.45; const talk = clamp(o.talk || 0, 0, 1);
  if (sp.features.includes('nose:pink')) circle(ctx, hx, hy + hh * 0.2, 6, acc, INK, 2);
  if (sp.features.includes('whiskers')) for (const sd of [-1, 1]) for (let i = 0; i < 2; i++) { ctx.strokeStyle = '#fff'; ctx.lineWidth = 2.5; ctx.beginPath(); ctx.moveTo(hx + sd * 10, hy + hh * 0.25 + i * 8); ctx.lineTo(hx + sd * hw * 1.2, hy + hh * 0.15 + i * 14); ctx.stroke(); }
  const m = sp.mouth;
  ctx.strokeStyle = INK; ctx.lineWidth = 3.5;
  if (m === 'beak' || m === 'beak:big' || m === 'beak:curved') { const bw = m === 'beak:big' ? 34 : 24; ctx.fillStyle = acc; ctx.beginPath(); ctx.moveTo(hx - bw, my - 14); ctx.lineTo(hx + bw, my - 14); ctx.lineTo(hx, my + 14 + talk * 10); ctx.closePath(); ctx.fill(); ctx.stroke(); }
  else if (m === 'snout' || m === 'snout:big') { ellipse(ctx, hx, my - 6, m === 'snout:big' ? 30 : 22, 16, shade(skin, 0.12), INK, 3); circle(ctx, hx, my - 12, 5, INK, null); if (talk > 0.3) { ellipse(ctx, hx, my + 10, 10, 6 * talk, INK, null); } }
  else if (m === 'grill') { ctx.fillStyle = '#1a1a24'; rr(ctx, hx - 22, my - 8, 44, 14 + talk * 6, 3); ctx.fill(); for (let i = -1; i <= 1; i++) { ctx.strokeStyle = acc; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(hx + i * 12, my - 8); ctx.lineTo(hx + i * 12, my + 6 + talk * 6); ctx.stroke(); } }
  else if (m === 'buck') { ctx.beginPath(); ctx.arc(hx, my - 6, 16, 0.2, Math.PI - 0.2); ctx.stroke(); ctx.fillStyle = '#fff'; ctx.fillRect(hx - 8, my + 2, 16, 12 + talk * 4); ctx.strokeRect(hx - 8, my + 2, 16, 12 + talk * 4); }
  else if (m === 'fishlips') { ellipse(ctx, hx, my, 16, 9 + talk * 6, '#ff8fa0', INK, 3); }
  else if (m === 'ooo') { ellipse(ctx, hx, my, 8 + talk * 4, 11 + talk * 6, INK, null); }
  else if (m === 'none') { /* nothing */ }
  else if (m === 'line') { ctx.beginPath(); ctx.moveTo(hx - 12, my); ctx.lineTo(hx + 12, my); ctx.stroke(); }
  else if (m === 'mandible') { for (const sd of [-1, 1]) { ctx.fillStyle = INK; ctx.beginPath(); ctx.moveTo(hx + sd * 6, my - 8); ctx.lineTo(hx + sd * 20, my + 12); ctx.lineTo(hx + sd * 10, my + 2); ctx.fill(); } }
  else if (m === 'teeth' || m === 'grin') { ctx.fillStyle = '#fff'; rr(ctx, hx - 22, my - 6, 44, 14 + talk * 8, 4); ctx.fill(); ctx.stroke(); ctx.beginPath(); for (let i = -1; i <= 1; i++) { ctx.moveTo(hx + i * 12, my - 6); ctx.lineTo(hx + i * 12, my + 8 + talk * 8); } ctx.stroke(); }
  else { // smile / smirk
    if (talk > 0.25) { ellipse(ctx, hx + (m === 'smirk' ? 6 : 0), my, 12, 6 + talk * 9, INK, null); ctx.fillStyle = '#ff8fa0'; ellipse(ctx, hx + (m === 'smirk' ? 6 : 0), my + 6 + talk * 4, 7, 3, '#ff8fa0', null); }
    else { ctx.beginPath(); ctx.arc(hx + (m === 'smirk' ? 8 : 0), my - 10, 18, 0.25, Math.PI - 0.25); ctx.stroke(); }
  }
  // accessories on the head
  if (o.accessory === 'apron') { ctx.fillStyle = '#ffffff'; rr(ctx, hx - hw * 0.7, hy - hh - 36, hw * 1.4, 34, 10); ctx.fill(); ctx.strokeStyle = INK; ctx.lineWidth = 3; ctx.stroke(); for (let i = -1; i <= 1; i++) circle(ctx, hx + i * hw * 0.42, hy - hh - 38, 16, '#ffffff', INK, 3); }
  if (o.accessory === 'coach') { ctx.strokeStyle = INK; ctx.lineWidth = 4; ctx.beginPath(); ctx.arc(hx, hy - 6, hw * 1.05, Math.PI * 1.1, Math.PI * 1.9); ctx.stroke(); circle(ctx, hx + hw * 1.02, hy + 4, 9, '#333', INK, 2); ctx.beginPath(); ctx.moveTo(hx + hw * 1.02, hy + 12); ctx.quadraticCurveTo(hx + hw * 0.8, hy + 40, hx + 30, hy + hh * 0.5); ctx.stroke(); circle(ctx, hx + 30, hy + hh * 0.5, 5, '#333', null); }
  if (o.accessory === 'gear') { ctx.fillStyle = '#ffd23f'; rr(ctx, hx - hw * 0.9, hy - hh * 0.75, hw * 1.8, 16, 6); ctx.fill(); ctx.strokeStyle = INK; ctx.lineWidth = 3; ctx.stroke(); ctx.fillStyle = INK; ctx.fillRect(hx - hw * 0.9, hy - hh * 0.75, hw * 1.8, 4); }
  if (o.accessory === 'crown') { ctx.fillStyle = '#ffd23f'; ctx.beginPath(); ctx.moveTo(hx - 26, hy - hh + 4); for (let i = 0; i < 5; i++) ctx.lineTo(hx - 26 + i * 13, hy - hh - (i % 2 ? 6 : 26)); ctx.lineTo(hx + 26, hy - hh + 4); ctx.closePath(); ctx.fill(); ctx.strokeStyle = INK; ctx.lineWidth = 3; ctx.stroke(); }
  // kid hair (no helmet in 2D)
  if (speciesId === 'kid') { const hc = o.hairColor || '#3a2a1a'; const style = o.hair || 'short'; ctx.fillStyle = hc; ctx.strokeStyle = INK; ctx.lineWidth = 3;
    if (style === 'curly') { for (let i = 0; i < 7; i++) { const a = Math.PI + i / 6 * Math.PI; circle(ctx, hx + Math.cos(a) * hw * 0.85, hy + Math.sin(a) * hh * 0.85 - 4, 15, hc, INK, 2.5); } }
    else if (style === 'ponytail') { ctx.beginPath(); ctx.ellipse(hx, hy - hh * 0.55, hw * 1.02, hh * 0.55, 0, Math.PI, Math.PI * 2); ctx.fill(); ctx.stroke(); rr(ctx, hx + hw * 0.55, hy - hh * 0.3, 20, 70, 10); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#ff5fa2'; rr(ctx, hx + hw * 0.55 - 2, hy - hh * 0.2, 24, 8, 3); ctx.fill(); }
    else if (style === 'braid') { ctx.beginPath(); ctx.ellipse(hx, hy - hh * 0.55, hw * 1.02, hh * 0.55, 0, Math.PI, Math.PI * 2); ctx.fill(); ctx.stroke(); for (let i = 0; i < 4; i++) circle(ctx, hx - hw * 0.7, hy + i * 18 - 6, 9, hc, INK, 2); }
    else if (style === 'bob') { ctx.beginPath(); ctx.ellipse(hx, hy - hh * 0.4, hw * 1.08, hh * 0.72, 0, Math.PI, Math.PI * 2); ctx.fill(); ctx.stroke(); for (const sd of [-1, 1]) { rr(ctx, hx + sd * hw * 0.85 - 10, hy - hh * 0.4, 20, hh * 0.9, 8); ctx.fill(); ctx.stroke(); } }
    else if (style === 'spiky') { for (let i = -2; i <= 2; i++) { ctx.beginPath(); ctx.moveTo(hx + i * 16 - 10, hy - hh * 0.75); ctx.lineTo(hx + i * 16 + (i * 3), hy - hh - 26); ctx.lineTo(hx + i * 16 + 10, hy - hh * 0.75); ctx.closePath(); ctx.fill(); ctx.stroke(); } }
    else if (style === 'buzz') { ctx.beginPath(); ctx.ellipse(hx, hy - hh * 0.6, hw * 1.0, hh * 0.45, 0, Math.PI, Math.PI * 2); ctx.fill(); }
    else { ctx.beginPath(); ctx.ellipse(hx, hy - hh * 0.55, hw * 1.02, hh * 0.55, 0, Math.PI, Math.PI * 2); ctx.fill(); ctx.stroke(); }
  }
  ctx.restore();
}

// ---------- sky, skyline, ground ----------
export function drawSky(ctx, theme, w, h, t = 0, horizon = 0.62) {
  const g = ctx.createLinearGradient(0, 0, 0, h * horizon); g.addColorStop(0, theme.sky[0]); g.addColorStop(0.6, theme.sky[1]); g.addColorStop(1, theme.sky[2]);
  ctx.fillStyle = g; ctx.fillRect(0, 0, w, h * horizon + 2);
  const rnd = makeRng(hashStr(theme.sky.join('')));
  for (const c of theme.celestial || []) {
    const cx = (c.x || 0.5) * w, cy = (c.y || 0.2) * h, r = (c.r || 0.05) * w;
    switch (c.type) {
      case 'stars': for (let i = 0; i < 140; i++) { ctx.fillStyle = `rgba(255,255,255,${0.4 + 0.6 * Math.abs(Math.sin(t * 2 + i))})`; const sx = rnd() * w, sy = rnd() * h * horizon * 0.9; ctx.fillRect(sx, sy, rnd() > 0.9 ? 3 : 2, rnd() > 0.9 ? 3 : 2); } break;
      case 'sun': { const gg = ctx.createRadialGradient(cx, cy, r * 0.6, cx, cy, r * 3.2); gg.addColorStop(0, rgba(c.colors[0], 0.9)); gg.addColorStop(0.3, rgba(c.colors[1], 0.35)); gg.addColorStop(1, rgba(c.colors[1], 0)); ctx.fillStyle = gg; ctx.fillRect(0, 0, w, h); circle(ctx, cx, cy, r, c.colors[1], null); circle(ctx, cx, cy, r * 0.8, c.colors[0], null); break; }
      case 'moon': case 'clockmoon': { circle(ctx, cx, cy, r, c.colors ? c.colors[0] : '#eee', null); ctx.fillStyle = c.colors ? c.colors[1] : '#aaa'; for (let i = 0; i < 5; i++) circle(ctx, cx + (rnd() - 0.5) * r * 1.3, cy + (rnd() - 0.5) * r * 1.3, r * rnd.range(0.08, 0.2), c.colors ? shade(c.colors[0], -0.2) : '#bbb', null); if (c.type === 'clockmoon') { circle(ctx, cx, cy, r * 0.9, '#fff8dc', INK, 4); ctx.strokeStyle = INK; ctx.lineWidth = 5; ctx.beginPath(); ctx.moveTo(cx, cy); ctx.lineTo(cx, cy - r * 0.6); ctx.moveTo(cx, cy); ctx.lineTo(cx + r * 0.45, cy + r * 0.2); ctx.stroke(); } break; }
      case 'earth': { circle(ctx, cx, cy, r, '#2f6fd6', null); ctx.fillStyle = '#3aa655'; for (let i = 0; i < 5; i++) ellipse(ctx, cx + (rnd() - 0.5) * r, cy + (rnd() - 0.5) * r, r * 0.3, r * 0.2, '#3aa655', null); ctx.fillStyle = 'rgba(255,255,255,0.7)'; for (let i = 0; i < 6; i++) ellipse(ctx, cx + (rnd() - 0.5) * r * 1.4, cy + (rnd() - 0.5) * r * 1.4, r * 0.25, r * 0.08, 'rgba(255,255,255,0.7)', null); ctx.save(); ctx.globalCompositeOperation = 'destination-in'; circle(ctx, cx, cy, r, '#000', null); ctx.restore(); ctx.globalCompositeOperation = 'source-over'; const gg = ctx.createRadialGradient(cx, cy, r * 0.9, cx, cy, r * 1.3); gg.addColorStop(0, 'rgba(142,197,255,0.5)'); gg.addColorStop(1, 'rgba(142,197,255,0)'); ctx.fillStyle = gg; ctx.fillRect(cx - r * 1.4, cy - r * 1.4, r * 2.8, r * 2.8); break; }
      case 'ring': case 'ringarc': { ctx.strokeStyle = rgba(c.colors ? c.colors[0] : '#fff', 0.8); ctx.lineWidth = c.type === 'ringarc' ? 26 : 10; ctx.beginPath(); ctx.ellipse(cx, cy + r * 0.4, r * 1.3, r * 0.5, -0.25, Math.PI * 1.05, Math.PI * 1.95); ctx.stroke(); ctx.strokeStyle = rgba('#ffffff', 0.5); ctx.lineWidth = 3; ctx.stroke(); break; }
      case 'aurora': for (let i = 0; i < 3; i++) { ctx.fillStyle = rgba(['#5ce65c', '#7fe3ff', '#c77dff'][i], 0.22); ctx.beginPath(); for (let x = 0; x <= w; x += 20) ctx.lineTo(x, h * 0.12 + i * 30 + Math.sin(x / 90 + t * 0.6 + i) * 28); for (let x = w; x >= 0; x -= 20) ctx.lineTo(x, h * 0.12 + i * 30 + 90 + Math.sin(x / 70 + t * 0.6 + i) * 22); ctx.fill(); } break;
      case 'blackhole': { const gg = ctx.createRadialGradient(cx, cy, r * 0.8, cx, cy, r * 2.4); gg.addColorStop(0, 'rgba(199,125,255,0.6)'); gg.addColorStop(0.5, 'rgba(255,158,92,0.2)'); gg.addColorStop(1, 'rgba(0,0,0,0)'); ctx.fillStyle = gg; ctx.fillRect(0, 0, w, h); ctx.strokeStyle = 'rgba(255,200,255,0.8)'; ctx.lineWidth = 6; ctx.beginPath(); ctx.ellipse(cx, cy, r * 1.9, r * 0.5, 0.3 + Math.sin(t * 0.2) * 0.05, 0, Math.PI * 2); ctx.stroke(); circle(ctx, cx, cy, r, '#000', null); break; }
      case 'nebula': { const gg = ctx.createRadialGradient(cx, cy, 0, cx, cy, r); gg.addColorStop(0, rgba(c.colors[0], 0.5)); gg.addColorStop(1, rgba(c.colors[1], 0)); ctx.fillStyle = gg; ctx.fillRect(0, 0, w, h); break; }
      case 'mirrorball': { circle(ctx, cx, cy, r, '#dddddd', INK, 3); for (let i = 0; i < 40; i++) { ctx.fillStyle = hsl((i * 47 + t * 60) % 360, 0.9, 0.6); ctx.fillRect(cx - r + (i % 8) * r / 4, cy - r + Math.floor(i / 8) * r / 2.5, r / 4 - 2, r / 2.5 - 2); } ctx.save(); ctx.globalCompositeOperation = 'destination-in'; ctx.restore(); ctx.strokeStyle = '#888'; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(cx, cy - r); ctx.lineTo(cx, 0); ctx.stroke(); break; }
      case 'searchlights': for (let i = 0; i < 3; i++) { ctx.fillStyle = 'rgba(255,255,255,0.08)'; ctx.beginPath(); const bx = w * (0.2 + i * 0.3); ctx.moveTo(bx, h * horizon); ctx.lineTo(bx + Math.sin(t * 0.7 + i) * 200 - 60, -20); ctx.lineTo(bx + Math.sin(t * 0.7 + i) * 200 + 60, -20); ctx.fill(); } break;
      case 'cottonclouds': for (let i = 0; i < 6; i++) { const bx = ((i * 0.19 + t * 0.006) % 1.2 - 0.1) * w, by = h * (0.1 + (i % 3) * 0.12); for (let k = 0; k < 5; k++) circle(ctx, bx + k * 34 - 60, by + Math.sin(k) * 10, 32 - Math.abs(k - 2) * 6, i % 2 ? '#ffd1e8' : '#e0f4ff', null); } break;
      case 'rays': for (let i = 0; i < 6; i++) { ctx.fillStyle = 'rgba(255,255,255,0.07)'; ctx.beginPath(); const bx = w * (0.1 + i * 0.16) + Math.sin(t * 0.3 + i) * 30; ctx.moveTo(bx - 20, 0); ctx.lineTo(bx + 20, 0); ctx.lineTo(bx + 120, h * horizon); ctx.lineTo(bx - 40, h * horizon); ctx.fill(); } break;
      case 'fish': for (let i = 0; i < 7; i++) { const fx = ((i * 0.17 + t * 0.03 * (1 + i % 3)) % 1.1) * w, fy = h * (0.08 + (i % 4) * 0.11); ctx.fillStyle = ['#ff9f1c', '#ff6b6b', '#ffe66d', '#2ec4b6'][i % 4]; ellipse(ctx, fx, fy, 14, 7, ctx.fillStyle, null); ctx.beginPath(); ctx.moveTo(fx - 12, fy); ctx.lineTo(fx - 22, fy - 7); ctx.lineTo(fx - 22, fy + 7); ctx.fill(); } break;
      case 'holograms': for (let i = 0; i < 3; i++) { ctx.fillStyle = rgba(['#2bf0ff', '#ff2bd6', '#ffe14d'][i], 0.25 + 0.1 * Math.sin(t * 3 + i)); rr(ctx, w * (0.15 + i * 0.32), h * 0.1 + Math.sin(t + i) * 8, 90, 50, 6); ctx.fill(); } break;
      case 'bats': for (let i = 0; i < 6; i++) { const bx = ((i * 0.15 + t * 0.05) % 1.1) * w, by = h * (0.1 + (i % 3) * 0.1) + Math.sin(t * 6 + i) * 6; ctx.strokeStyle = '#0e0a1a'; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(bx - 12, by); ctx.quadraticCurveTo(bx - 6, by - 8 + Math.sin(t * 20) * 4, bx, by); ctx.quadraticCurveTo(bx + 6, by - 8 + Math.sin(t * 20) * 4, bx + 12, by); ctx.stroke(); } break;
      case 'butterflies': for (let i = 0; i < 6; i++) { const bx = ((i * 0.17 + t * 0.02) % 1.1) * w, by = h * (0.2 + (i % 3) * 0.12) + Math.sin(t * 3 + i) * 12; ctx.fillStyle = ['#ff7bac', '#ffe66d', '#c77dff'][i % 3]; const fl = Math.abs(Math.sin(t * 10 + i)); ellipse(ctx, bx - 6 * fl, by, 7 * fl + 1, 6, ctx.fillStyle, null); ellipse(ctx, bx + 6 * fl, by, 7 * fl + 1, 6, ctx.fillStyle, null); } break;
      case 'volcano': { ctx.fillStyle = '#2a2a2e'; ctx.beginPath(); ctx.moveTo(w * 0.62, h * horizon); ctx.lineTo(w * 0.75, h * 0.28); ctx.lineTo(w * 0.8, h * 0.28); ctx.lineTo(w * 0.94, h * horizon); ctx.fill(); ctx.fillStyle = '#ff6a1f'; ctx.fillRect(w * 0.75, h * 0.27, w * 0.05, 6); for (let i = 0; i < 4; i++) circle(ctx, w * 0.775 + Math.sin(t + i) * 20, h * 0.22 - i * 22, 14 + i * 5, `rgba(90,90,90,${0.5 - i * 0.1})`, null); break; }
      case 'gears': for (let i = 0; i < 4; i++) { const gx = w * (0.15 + i * 0.25), gy = h * 0.18, gr = 40 + (i % 2) * 20; ctx.fillStyle = 'rgba(110,117,129,0.55)'; ctx.beginPath(); for (let k = 0; k < 24; k++) { const a = k / 24 * Math.PI * 2 + t * (i % 2 ? 0.3 : -0.3); const rad = k % 2 ? gr : gr * 0.82; ctx.lineTo(gx + Math.cos(a) * rad, gy + Math.sin(a) * rad); } ctx.closePath(); ctx.fill(); circle(ctx, gx, gy, gr * 0.3, theme.sky[1], null); } break;
      case 'bands': for (let i = 0; i < 6; i++) { ctx.fillStyle = rgba(i % 2 ? '#ffffff' : theme.palette[1], 0.12); ctx.beginPath(); for (let x = 0; x <= w; x += 20) ctx.lineTo(x, h * 0.08 * i + Math.sin(x / 120 + i) * 12); for (let x = w; x >= 0; x -= 20) ctx.lineTo(x, h * 0.08 * i + 30 + Math.sin(x / 100 + i) * 10); ctx.fill(); } break;
      case 'beam': { ctx.fillStyle = 'rgba(127,255,212,0.15)'; ctx.beginPath(); ctx.moveTo(w * 0.45, 0); ctx.lineTo(w * 0.55, 0); ctx.lineTo(w * 0.7, h * horizon); ctx.lineTo(w * 0.3, h * horizon); ctx.fill(); break; }
      case 'rainbow': { for (let i = 0; i < 6; i++) { ctx.strokeStyle = rgba(hsl(i * 55, 0.9, 0.6), 0.45); ctx.lineWidth = 10; ctx.beginPath(); ctx.arc(w * 0.5, h * horizon, w * 0.42 - i * 10, Math.PI, Math.PI * 2); ctx.stroke(); } break; }
    }
  }
}
export function drawSkyline(ctx, kind, w, hy, palette, seed = 1, t = 0) {
  const rnd = makeRng(hashStr(kind + seed)); const dark = shade(palette[3] || '#2a2a4a', -0.1); const mid = mix(palette[3] || '#2a2a4a', palette[0], 0.35);
  ctx.save();
  const spikes = (n, minH, maxH, color, wid) => { ctx.fillStyle = color; ctx.beginPath(); ctx.moveTo(0, hy); for (let i = 0; i <= n; i++) { const x = i / n * w; ctx.lineTo(x - wid / 2, hy); ctx.lineTo(x, hy - rnd.range(minH, maxH)); ctx.lineTo(x + wid / 2, hy); } ctx.lineTo(w, hy); ctx.fill(); };
  const domes = (n, color, rmin, rmax) => { ctx.fillStyle = color; for (let i = 0; i < n; i++) { const x = rnd() * w, r = rnd.range(rmin, rmax); ctx.beginPath(); ctx.arc(x, hy, r, Math.PI, 0); ctx.fill(); } };
  const boxes = (n, color, wmin, wmax, hmin, hmax, lights) => { for (let i = 0; i < n; i++) { const bw = rnd.range(wmin, wmax), bh = rnd.range(hmin, hmax), x = rnd() * (w - bw); ctx.fillStyle = color; ctx.fillRect(x, hy - bh, bw, bh); if (lights) for (let k = 0; k < bh / 14; k++) for (let j = 0; j < bw / 14; j++) if (rnd() < 0.5) { ctx.fillStyle = rnd.pick(lights); ctx.fillRect(x + 4 + j * 14, hy - bh + 6 + k * 14, 6, 8); } } };
  switch (kind) {
    case 'suburb': boxes(9, mid, 70, 120, 50, 80); ctx.fillStyle = mid; for (let i = 0; i < 9; i++) { const x = rnd() * w; ctx.beginPath(); ctx.moveTo(x - 60, hy - 60); ctx.lineTo(x, hy - 110); ctx.lineTo(x + 60, hy - 60); ctx.fill(); } domes(14, '#3f8a3f', 20, 50); break;
    case 'domes': domes(10, mid, 40, 130); domes(6, shade(mid, 0.15), 20, 60); break;
    case 'mesas': spikes(7, 60, 160, mid, 200); break;
    case 'clouds': domes(12, 'rgba(255,255,255,0.8)', 40, 110); break;
    case 'icebergs': spikes(12, 60, 200, '#bfe6ff', 90); spikes(8, 30, 100, '#e6f7ff', 60); break;
    case 'volcanoes': spikes(5, 120, 230, '#1a1010', 320); ctx.fillStyle = '#ff6a1f'; for (let i = 0; i < 5; i++) circle(ctx, (i + 0.5) / 5 * w + rnd.range(-40, 40), hy - rnd.range(120, 220), 8 + Math.sin(t * 4 + i) * 2, '#ff9a3a', null); break;
    case 'mushrooms': for (let i = 0; i < 9; i++) { const x = rnd() * w, hgt = rnd.range(80, 220), r = rnd.range(40, 90); ctx.fillStyle = mid; ctx.fillRect(x - r * 0.3, hy - hgt, r * 0.6, hgt); ctx.fillStyle = shade(mid, 0.2); ctx.beginPath(); ctx.ellipse(x, hy - hgt, r, r * 0.5, 0, Math.PI, 0); ctx.fill(); } break;
    case 'coral': for (let i = 0; i < 14; i++) { const x = rnd() * w, hgt = rnd.range(60, 200); ctx.strokeStyle = rgba(rnd.pick(palette), 0.7); ctx.lineWidth = rnd.range(8, 20); ctx.beginPath(); ctx.moveTo(x, hy); ctx.quadraticCurveTo(x + rnd.range(-40, 40), hy - hgt * 0.6, x + rnd.range(-30, 30), hy - hgt); ctx.stroke(); } break;
    case 'dunes': for (let i = 0; i < 5; i++) { ctx.fillStyle = mix(palette[0], palette[3], i * 0.15); ctx.beginPath(); ctx.moveTo(0, hy); for (let x = 0; x <= w; x += 30) ctx.lineTo(x, hy - 40 - i * 15 - Math.sin(x / (160 + i * 40) + i) * 40); ctx.lineTo(w, hy); ctx.fill(); } break;
    case 'candy': for (let i = 0; i < 10; i++) { const x = rnd() * w, hgt = rnd.range(80, 200); ctx.fillStyle = '#ffffff'; ctx.fillRect(x - 6, hy - hgt, 12, hgt); circle(ctx, x, hy - hgt, rnd.range(30, 55), rnd.pick(palette), null); } break;
    case 'crystals': spikes(14, 80, 260, rgba('#d9b3ff', 0.75), 60); spikes(10, 40, 140, rgba('#a8e6ff', 0.8), 40); break;
    case 'city': boxes(16, dark, 40, 90, 120, 320, ['#2bf0ff', '#ff2bd6', '#ffe14d']); break;
    case 'junk': boxes(22, mid, 30, 80, 30, 120); for (let i = 0; i < 8; i++) { ctx.fillStyle = '#1a1a1a'; ellipse(ctx, rnd() * w, hy - 20, 22, 22, '#1a1a1a', null); } break;
    case 'hive': for (let i = 0; i < 12; i++) { const x = rnd() * w, hgt = rnd.range(60, 200), r = rnd.range(30, 60); ctx.fillStyle = mix('#f0b323', '#7a5200', rnd() * 0.5); ctx.beginPath(); for (let k = 0; k < 6; k++) { const a = k / 6 * Math.PI * 2; ctx.lineTo(x + Math.cos(a) * r, hy - hgt + Math.sin(a) * r); } ctx.fill(); ctx.fillRect(x - r * 0.86, hy - hgt, r * 1.72, hgt); } break;
    case 'mansions': boxes(7, '#1a1428', 60, 120, 120, 260); ctx.fillStyle = '#1a1428'; for (let i = 0; i < 7; i++) { const x = rnd() * w; ctx.beginPath(); ctx.moveTo(x - 50, hy - 180); ctx.lineTo(x, hy - 280); ctx.lineTo(x + 50, hy - 180); ctx.fill(); } ctx.fillStyle = '#c6ff5a'; for (let i = 0; i < 30; i++) ctx.fillRect(rnd() * w, hy - rnd.range(40, 200), 6, 9); break;
    case 'jungle': domes(16, '#1c4d1e', 60, 160); for (let i = 0; i < 10; i++) { const x = rnd() * w, hgt = rnd.range(100, 240); ctx.strokeStyle = '#2a3a1e'; ctx.lineWidth = 10; ctx.beginPath(); ctx.moveTo(x, hy); ctx.quadraticCurveTo(x + 20, hy - hgt * 0.5, x, hy - hgt); ctx.stroke(); for (let k = 0; k < 6; k++) { ctx.strokeStyle = '#2f7a32'; ctx.lineWidth = 8; ctx.beginPath(); ctx.moveTo(x, hy - hgt); ctx.quadraticCurveTo(x + Math.cos(k) * 60, hy - hgt - 20, x + Math.cos(k) * 90, hy - hgt + 30); ctx.stroke(); } } break;
    case 'cheese': for (let i = 0; i < 8; i++) { const x = rnd() * w, hgt = rnd.range(60, 160); ctx.fillStyle = mid; ctx.beginPath(); ctx.moveTo(x - 80, hy); ctx.lineTo(x + 80, hy); ctx.lineTo(x + 60, hy - hgt); ctx.lineTo(x - 60, hy - hgt * 0.7); ctx.fill(); ctx.fillStyle = shade(mid, -0.3); for (let k = 0; k < 4; k++) circle(ctx, x + rnd.range(-50, 50), hy - rnd.range(10, hgt * 0.6), rnd.range(6, 16), shade(mid, -0.3), null); } break;
    case 'ships': for (let i = 0; i < 6; i++) { const x = rnd() * w; ctx.fillStyle = dark; ctx.beginPath(); ctx.moveTo(x - 90, hy - 30); ctx.lineTo(x + 90, hy - 30); ctx.lineTo(x + 70, hy); ctx.lineTo(x - 70, hy); ctx.fill(); ctx.fillRect(x - 4, hy - 190, 8, 160); ctx.fillStyle = '#d9d9d9'; ctx.beginPath(); ctx.moveTo(x + 4, hy - 180); ctx.lineTo(x + 70, hy - 100); ctx.lineTo(x + 4, hy - 90); ctx.fill(); } break;
    case 'casino': boxes(12, '#1a1030', 50, 110, 100, 300, ['#ffd700', '#e0115f', '#2bf0ff']); break;
    case 'flowers': for (let i = 0; i < 10; i++) { const x = rnd() * w, hgt = rnd.range(90, 220); ctx.strokeStyle = '#2a5a2a'; ctx.lineWidth = 10; ctx.beginPath(); ctx.moveTo(x, hy); ctx.lineTo(x, hy - hgt); ctx.stroke(); const c = rnd.pick(['#ff7bac', '#c77dff', '#ff6b6b', '#ffb347']); for (let k = 0; k < 7; k++) { const a = k / 7 * Math.PI * 2; circle(ctx, x + Math.cos(a) * 28, hy - hgt + Math.sin(a) * 28, 16, c, null); } circle(ctx, x, hy - hgt, 14, '#ffe66d', null); } break;
    case 'factory': boxes(8, dark, 80, 160, 60, 140); for (let i = 0; i < 8; i++) { const x = rnd() * w; ctx.fillStyle = mid; ctx.fillRect(x - 12, hy - 260, 24, 260); for (let k = 0; k < 3; k++) circle(ctx, x + k * 12 + Math.sin(t + k) * 6, hy - 270 - k * 26, 16 + k * 6, `rgba(180,180,190,${0.5 - k * 0.12})`, null); } break;
    case 'balloons': for (let i = 0; i < 9; i++) { const x = rnd() * w, y = hy - rnd.range(80, 260); const c = rnd.pick(palette); ellipse(ctx, x, y, 34, 42, c, INK, 2); ctx.fillStyle = '#8a6a3a'; ctx.fillRect(x - 12, y + 62, 24, 16); ctx.strokeStyle = INK; ctx.lineWidth = 1.5; ctx.beginPath(); ctx.moveTo(x - 14, y + 34); ctx.lineTo(x - 12, y + 62); ctx.moveTo(x + 14, y + 34); ctx.lineTo(x + 12, y + 62); ctx.stroke(); } domes(4, mid, 80, 160); break;
    case 'bubbles': for (let i = 0; i < 16; i++) { const x = rnd() * w, y = hy - rnd.range(20, 260), r = rnd.range(14, 60); circle(ctx, x, y, r, 'rgba(255,255,255,0.15)', 'rgba(255,255,255,0.6)', 2); circle(ctx, x - r * 0.4, y - r * 0.4, r * 0.18, 'rgba(255,255,255,0.8)', null); } break;
    case 'disco': boxes(10, '#2a0a4a', 60, 120, 80, 220, ['#ff2bd6', '#ffd700', '#2bf0ff']); break;
    case 'books': for (let i = 0; i < 9; i++) { const x = rnd() * w; let y = hy; for (let k = 0; k < rnd.int(3, 6); k++) { const bw = rnd.range(60, 110), bh = rnd.range(16, 28); ctx.fillStyle = rnd.pick(['#a83232', '#3a5a8a', '#4a7a3a', '#8b6b4a', '#5a3a8a']); ctx.fillRect(x - bw / 2, y - bh, bw, bh); ctx.fillStyle = '#f0e0c0'; ctx.fillRect(x - bw / 2 + 4, y - bh + 3, bw - 8, 3); y -= bh; } } break;
    case 'goo': domes(12, mid, 40, 140); ctx.fillStyle = mid; for (let i = 0; i < 8; i++) { const x = rnd() * w; ctx.beginPath(); ctx.moveTo(x - 10, hy - 100); ctx.quadraticCurveTo(x, hy - 20 + Math.sin(t + i) * 10, x + 10, hy - 100); ctx.fill(); } break;
    case 'pizza': for (let i = 0; i < 7; i++) { const x = rnd() * w, hgt = rnd.range(80, 180); ctx.fillStyle = '#e0a040'; ctx.beginPath(); ctx.moveTo(x, hy); ctx.lineTo(x - 70, hy - hgt); ctx.lineTo(x + 70, hy - hgt); ctx.fill(); ctx.fillStyle = '#c8282a'; ctx.beginPath(); ctx.moveTo(x, hy - 20); ctx.lineTo(x - 56, hy - hgt + 14); ctx.lineTo(x + 56, hy - hgt + 14); ctx.fill(); for (let k = 0; k < 3; k++) circle(ctx, x + rnd.range(-30, 30), hy - rnd.range(40, hgt - 30), 9, '#8a1a1c', null); } break;
    case 'ring': ctx.strokeStyle = rgba('#dfe4ee', 0.8); ctx.lineWidth = 40; ctx.beginPath(); ctx.ellipse(w / 2, hy + 80, w * 0.55, 260, 0, Math.PI * 1.05, Math.PI * 1.95); ctx.stroke(); boxes(10, mid, 30, 60, 60, 180, ['#3ee8ff']); break;
    case 'void': for (let i = 0; i < 10; i++) { const x = rnd() * w, y = hy - rnd.range(40, 240), r = rnd.range(20, 60); ctx.fillStyle = '#2b1b4a'; ctx.beginPath(); for (let k = 0; k < 7; k++) { const a = k / 7 * Math.PI * 2; ctx.lineTo(x + Math.cos(a) * r * rnd.range(0.7, 1.2), y + Math.sin(a) * r * rnd.range(0.7, 1.2)); } ctx.fill(); ctx.strokeStyle = '#c77dff'; ctx.lineWidth = 2; ctx.stroke(); } break;
    case 'clocks': boxes(8, mid, 50, 90, 140, 320); for (let i = 0; i < 8; i++) { const x = rnd() * w, y = hy - rnd.range(150, 300); circle(ctx, x, y, 26, '#fff8dc', INK, 3); ctx.strokeStyle = INK; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(x, y); ctx.lineTo(x, y - 16); ctx.moveTo(x, y); ctx.lineTo(x + 12, y + 4); ctx.stroke(); } break;
    case 'ship': boxes(14, mid, 40, 100, 100, 300, ['#7fffd4', '#ff5ce6']); for (let i = 0; i < 12; i++) { ctx.fillStyle = rgba('#7fffd4', 0.5); ctx.fillRect(rnd() * w, hy - rnd.range(50, 280), rnd.range(30, 90), 4); } break;
    default: spikes(10, 60, 200, mid, 140);
  }
  ctx.restore();
}
export function drawGround(ctx, groundType, w, y0, h, color, seed = 1, t = 0) {
  const rnd = makeRng(hashStr(groundType + seed));
  const g = ctx.createLinearGradient(0, y0, 0, y0 + h); g.addColorStop(0, shade(color, 0.12)); g.addColorStop(1, shade(color, -0.25)); ctx.fillStyle = g; ctx.fillRect(0, y0, w, h);
  const spots = (n, col, rmin, rmax, sy = 0.35) => { for (let i = 0; i < n; i++) { const y = y0 + rnd() * h; const sc = 0.4 + (y - y0) / h; ellipse(ctx, rnd() * w, y, rnd.range(rmin, rmax) * sc, rnd.range(rmin, rmax) * sc * sy, col, null); } };
  switch (groundType) {
    case 'lawn': spots(30, shade(color, 0.15), 20, 60, 0.3); break;
    case 'craters': for (let i = 0; i < 16; i++) { const y = y0 + rnd() * h; const sc = 0.4 + (y - y0) / h; const x = rnd() * w, r = rnd.range(14, 40) * sc; ellipse(ctx, x, y, r, r * 0.35, shade(color, -0.2), shade(color, 0.25), 3); } break;
    case 'dust': case 'sand': spots(60, shade(color, -0.12), 6, 30, 0.3); spots(40, shade(color, 0.15), 6, 24, 0.3); break;
    case 'clouds': spots(20, 'rgba(255,255,255,0.45)', 30, 90, 0.4); break;
    case 'ice': for (let i = 0; i < 30; i++) { ctx.strokeStyle = 'rgba(255,255,255,0.6)'; ctx.lineWidth = 2; ctx.beginPath(); let x = rnd() * w, y = y0 + rnd() * h; ctx.moveTo(x, y); for (let k = 0; k < 4; k++) { x += rnd.range(-60, 60); y += rnd.range(-20, 20); ctx.lineTo(x, y); } ctx.stroke(); } break;
    case 'lava': spots(12, '#ff6a1f', 20, 70, 0.3); spots(8, '#ffd166', 6, 18, 0.3); break;
    case 'moss': case 'jungle': case 'garden': spots(40, shade(color, 0.15), 10, 40, 0.35); spots(20, shade(color, -0.2), 10, 30, 0.35); break;
    case 'seafloor': spots(40, shade(color, -0.1), 8, 30, 0.3); for (let i = 0; i < 20; i++) circle(ctx, rnd() * w, y0 + rnd() * h, rnd.range(3, 7), '#ff9f1c', null); break;
    case 'candy': for (let i = 0; i < 26; i++) { const x = rnd() * w, y = y0 + rnd() * h; circle(ctx, x, y, rnd.range(6, 14), rnd.pick(['#ff4f79', '#ffd23f', '#57e86b', '#4dc9ff']), null); } break;
    case 'crystal': for (let i = 0; i < 26; i++) { const x = rnd() * w, y = y0 + rnd() * h; ctx.fillStyle = rgba(rnd.pick(['#a8e6ff', '#d9b3ff', '#ffffff']), 0.7); ctx.beginPath(); ctx.moveTo(x, y - 26); ctx.lineTo(x + 10, y); ctx.lineTo(x - 10, y); ctx.fill(); } break;
    case 'street': for (let i = 0; i < 12; i++) { ctx.fillStyle = rgba(rnd.pick(['#2bf0ff', '#ff2bd6', '#ffe14d']), 0.35); ctx.fillRect(rnd() * w, y0 + rnd() * h, rnd.range(40, 140), 3); } spots(20, 'rgba(255,255,255,0.08)', 30, 90, 0.3); break;
    case 'junk': for (let i = 0; i < 30; i++) { ctx.fillStyle = rnd.pick(['#a0632b', '#7d7f86', '#5d6068', '#e8c25a']); const y = y0 + rnd() * h; ctx.fillRect(rnd() * w, y, rnd.range(10, 40), rnd.range(6, 18)); } break;
    case 'honey': spots(20, 'rgba(255,220,100,0.7)', 20, 60, 0.3); break;
    case 'graveyard': for (let i = 0; i < 14; i++) { const x = rnd() * w, y = y0 + rnd() * h; ctx.fillStyle = '#6e6a8a'; rr(ctx, x - 12, y - 30, 24, 30, 8); ctx.fill(); } spots(20, 'rgba(0,0,0,0.15)', 20, 60, 0.3); break;
    case 'cheese': for (let i = 0; i < 24; i++) { const y = y0 + rnd() * h; ellipse(ctx, rnd() * w, y, rnd.range(8, 22), rnd.range(4, 10), shade(color, -0.35), null); } break;
    case 'deck': for (let i = 0; i < h / 22; i++) { ctx.fillStyle = shade(color, (i % 2) * 0.08 - 0.04); ctx.fillRect(0, y0 + i * 22, w, 21); } break;
    case 'carpet': for (let i = 0; i < 40; i++) { ctx.fillStyle = rgba('#ffd700', 0.35); ctx.beginPath(); const x = rnd() * w, y = y0 + rnd() * h; ctx.moveTo(x, y - 8); ctx.lineTo(x + 8, y); ctx.lineTo(x, y + 8); ctx.lineTo(x - 8, y); ctx.fill(); } break;
    case 'factory': for (let x = 0; x < w; x += 60) for (let y = y0; y < y0 + h; y += 40) { ctx.strokeStyle = shade(color, -0.25); ctx.lineWidth = 2; ctx.strokeRect(x, y, 60, 40); circle(ctx, x + 6, y + 6, 2, shade(color, 0.3), null); } break;
    case 'island': spots(20, shade(color, 0.2), 20, 70, 0.3); break;
    case 'bubbles': for (let i = 0; i < 26; i++) { const x = rnd() * w, y = y0 + rnd() * h; circle(ctx, x, y, rnd.range(4, 14), 'rgba(255,255,255,0.25)', 'rgba(255,255,255,0.6)', 2); } break;
    case 'dancefloor': for (let x = 0; x < w; x += 50) for (let y = y0; y < y0 + h; y += 32) { ctx.fillStyle = hsl(((x + y) * 0.7 + t * 120) % 360, 0.85, 0.5); ctx.globalAlpha = 0.35; ctx.fillRect(x + 1, y + 1, 48, 30); } ctx.globalAlpha = 1; break;
    case 'library': for (let i = 0; i < h / 26; i++) { ctx.fillStyle = shade(color, (i % 2) * 0.06); ctx.fillRect(0, y0 + i * 26, w, 25); } break;
    case 'goo': spots(30, shade(color, 0.18), 10, 50, 0.3); spots(20, 'rgba(255,255,255,0.25)', 3, 8, 0.6); break;
    case 'pizza': spots(20, '#c8282a', 14, 40, 0.35); for (let i = 0; i < 16; i++) circle(ctx, rnd() * w, y0 + rnd() * h, rnd.range(5, 12), '#8a1a1c', null); break;
    case 'ring': for (let x = 0; x < w; x += 80) { ctx.fillStyle = rgba('#3ee8ff', 0.25); ctx.fillRect(x, y0, 3, h); } break;
    case 'void': spots(20, 'rgba(199,125,255,0.25)', 10, 50, 0.3); break;
    case 'clock': for (let i = 0; i < 10; i++) { const x = rnd() * w, y = y0 + rnd() * h; ctx.strokeStyle = shade(color, -0.3); ctx.lineWidth = 3; ctx.beginPath(); for (let k = 0; k < 16; k++) { const a = k / 16 * Math.PI * 2; const rad = k % 2 ? 22 : 17; ctx.lineTo(x + Math.cos(a) * rad, y + Math.sin(a) * rad * 0.5); } ctx.closePath(); ctx.stroke(); } break;
    case 'ship': for (let x = 0; x < w; x += 90) { ctx.fillStyle = rgba('#7fffd4', 0.2); ctx.fillRect(x, y0, 4, h); } for (let y = y0; y < y0 + h; y += 40) { ctx.fillStyle = rgba('#7fffd4', 0.15); ctx.fillRect(0, y, w, 3); } break;
    default: spots(30, shade(color, 0.12), 10, 40, 0.3);
  }
}
export function drawParticles(ctx, type, w, h, t, seed = 3, n = 60) {
  if (!type || type === 'none') return; const rnd = makeRng(hashStr(type + seed));
  const cfg = { snow: ['#ffffff', 0, 40, 4], embers: ['#ffb347', 0, -50, 3], spores: ['#c6ff5a', 10, -12, 3], bubbles: ['#dff6ff', 0, -40, 5], rain: ['#9fd8ff', 60, 500, 2], dust: ['#e0a070', 90, 6, 3], sand: ['#f0c070', 140, 10, 3], confetti: [null, 20, 50, 4], sparkles: ['#ffffff', 0, -5, 3], petals: ['#ff7bac', 30, 40, 5], leaves: ['#6ccf70', 40, 45, 5], crumbs: ['#ffe680', 0, 60, 3], coins: ['#ffd700', 0, 80, 5], steam: ['#dddddd', 5, -30, 8], pages: ['#f0e0c0', 60, 25, 6], drips: ['#9dff5c', 0, 120, 4], pollen: ['#ffe08a', 25, -8, 3], sparks: ['#ffb060', 0, 200, 2], stars: ['#ffffff', 0, 0, 2], fog: ['rgba(255,255,255,0.5)', 20, 0, 40] }[type];
  if (!cfg) return; const [col, vx, vy, sz] = cfg;
  for (let i = 0; i < n; i++) { const ox = rnd() * w, oy = rnd() * h, ph = rnd() * 10; const x = ((ox + vx * t + Math.sin(t * 1.3 + ph) * 18) % (w + 40) + w + 40) % (w + 40) - 20; const y = ((oy + vy * t) % (h + 40) + h + 40) % (h + 40) - 20; ctx.fillStyle = col || hsl((i * 37) % 360, 0.9, 0.6); ctx.globalAlpha = type === 'fog' ? 0.12 : 0.85; if (type === 'confetti' || type === 'pages' || type === 'leaves') { ctx.save(); ctx.translate(x, y); ctx.rotate(t * 3 + ph); ctx.fillRect(-sz, -sz / 2, sz * 2, sz); ctx.restore(); } else if (type === 'rain') ctx.fillRect(x, y, 2, 14); else circle(ctx, x, y, sz * (0.6 + 0.4 * Math.sin(t * 2 + ph)), ctx.fillStyle, null); }
  ctx.globalAlpha = 1;
}

// ---------- buildings ----------
// draws a 2.5D shop building with its footprint at (x, y) baseline center, width w, height h.
export function drawBuilding(ctx, style, x, y, w, h, palette, o = {}) {
  const rnd = makeRng(hashStr(style + (o.seed || 1))); const [c0, c1, c2, c3] = palette; const base = o.color || c0; const side = shade(base, -0.28); const roofC = o.roof || c1; const d = w * 0.22; // side depth
  ctx.save(); ctx.lineJoin = 'round'; ctx.strokeStyle = INK; ctx.lineWidth = 3.5;
  const front = (fill) => { ctx.fillStyle = fill; ctx.fillRect(x - w / 2, y - h, w, h); ctx.strokeRect(x - w / 2, y - h, w, h); };
  const sideFace = (fill) => { ctx.fillStyle = fill; ctx.beginPath(); ctx.moveTo(x + w / 2, y - h); ctx.lineTo(x + w / 2 + d, y - h - d * 0.5); ctx.lineTo(x + w / 2 + d, y - d * 0.5); ctx.lineTo(x + w / 2, y); ctx.closePath(); ctx.fill(); ctx.stroke(); };
  const gable = (fill, over = 10) => { ctx.fillStyle = fill; ctx.beginPath(); ctx.moveTo(x - w / 2 - over, y - h); ctx.lineTo(x, y - h - h * 0.45); ctx.lineTo(x + w / 2 + over, y - h); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.beginPath(); ctx.moveTo(x + w / 2 + over, y - h); ctx.lineTo(x + w / 2 + over + d, y - h - d * 0.5); ctx.lineTo(x + d, y - h - h * 0.45 - d * 0.5); ctx.lineTo(x, y - h - h * 0.45); ctx.closePath(); ctx.fillStyle = shade(fill, -0.25); ctx.fill(); ctx.stroke(); };
  const domeTop = (fill, rx = w / 2, ry = h * 0.45) => { ctx.fillStyle = fill; ctx.beginPath(); ctx.ellipse(x, y - h, rx, ry, 0, Math.PI, 0); ctx.closePath(); ctx.fill(); ctx.stroke(); };
  const windows = (n, col = '#8ec5ff', glow = false) => { for (let i = 0; i < n; i++) { const wx = x - w / 2 + w * (i + 0.5) / n - 12; const wy = y - h * 0.62; if (glow) { ctx.shadowColor = col; ctx.shadowBlur = 14; } ctx.fillStyle = col; rr(ctx, wx, wy, 24, 26, 5); ctx.fill(); ctx.shadowBlur = 0; ctx.strokeStyle = INK; ctx.lineWidth = 2.5; ctx.stroke(); ctx.beginPath(); ctx.moveTo(wx + 12, wy); ctx.lineTo(wx + 12, wy + 26); ctx.moveTo(wx, wy + 13); ctx.lineTo(wx + 24, wy + 13); ctx.stroke(); } ctx.lineWidth = 3.5; };
  const door = () => { ctx.fillStyle = shade(base, -0.5); rr(ctx, x - 16, y - 44, 32, 44, 6); ctx.fill(); ctx.stroke(); circle(ctx, x + 8, y - 22, 3, '#ffd23f', null); };
  switch (style) {
    case 'suburb': sideFace(side); front(base); gable(roofC); windows(2); door(); ctx.fillStyle = shade(roofC, -0.2); ctx.fillRect(x + w * 0.2, y - h - h * 0.5, 14, h * 0.25); break;
    case 'dome': ctx.fillStyle = base; ctx.beginPath(); ctx.ellipse(x, y, w / 2 + 6, h * 0.95, 0, Math.PI, 0); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.strokeStyle = rgba(INK, 0.35); ctx.lineWidth = 2; for (let i = 1; i < 4; i++) { ctx.beginPath(); ctx.ellipse(x, y, (w / 2 + 6) * i / 4, h * 0.95 * i / 4 + h * 0.6 * (1 - i / 4), 0, Math.PI, 0); ctx.stroke(); } ctx.strokeStyle = INK; ctx.lineWidth = 3.5; windows(2, c2, true); door(); ctx.fillStyle = '#8b90a8'; ctx.fillRect(x - 3, y - h * 0.95 - 30, 6, 30); circle(ctx, x, y - h * 0.95 - 34, 6, '#ff6b7a', INK, 2); break;
    case 'habitat': sideFace(side); ctx.fillStyle = base; rr(ctx, x - w / 2, y - h, w, h, 26); ctx.fill(); ctx.stroke(); ctx.fillStyle = shade(base, -0.15); rr(ctx, x - w / 2 + 8, y - h + 8, w - 16, 14, 7); ctx.fill(); windows(2, '#ffd39a', true); door(); ctx.fillStyle = '#8b90a8'; ctx.fillRect(x - w / 2 + 10, y - h - 24, 4, 24); ctx.fillRect(x - w / 2 - 2, y - h - 26, 28, 4); break;
    case 'cloudhouse': for (let i = 0; i < 5; i++) circle(ctx, x - w / 2 + w * i / 4, y - h * 0.9 + Math.abs(i - 2) * 8, w * 0.22, '#fff8e6', INK); front(rgba('#fff8e6', 0.95)); ctx.fillStyle = '#fff8e6'; ctx.fillRect(x - w / 2 + 2, y - h - 4, w - 4, 30); windows(2, '#7fd0ff'); door(); break;
    case 'igloo': ctx.fillStyle = '#eef8ff'; ctx.beginPath(); ctx.ellipse(x, y, w / 2 + 8, h * 0.9, 0, Math.PI, 0); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.strokeStyle = rgba(INK, 0.3); ctx.lineWidth = 2; for (let r = 1; r < 4; r++) { ctx.beginPath(); ctx.ellipse(x, y, (w / 2 + 8), h * 0.9 - r * 22, 0, Math.PI, 0); ctx.stroke(); } ctx.strokeStyle = INK; ctx.lineWidth = 3.5; ctx.fillStyle = '#cfeeff'; rr(ctx, x - 22, y - 48, 44, 48, 20); ctx.fill(); ctx.stroke(); ctx.fillStyle = shade('#cfeeff', -0.5); rr(ctx, x - 14, y - 36, 28, 36, 14); ctx.fill(); break;
    case 'obsidian': sideFace('#151518'); ctx.fillStyle = '#2a2a2e'; ctx.beginPath(); ctx.moveTo(x - w / 2, y); ctx.lineTo(x - w / 2 + 6, y - h * 0.8); ctx.lineTo(x - w * 0.2, y - h * 1.2); ctx.lineTo(x + w * 0.15, y - h * 0.95); ctx.lineTo(x + w / 2, y - h * 1.1); ctx.lineTo(x + w / 2, y); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.strokeStyle = '#ff6a1f'; ctx.lineWidth = 3; ctx.shadowColor = '#ff6a1f'; ctx.shadowBlur = 12; ctx.beginPath(); ctx.moveTo(x - w * 0.3, y - h * 0.3); ctx.lineTo(x - w * 0.1, y - h * 0.6); ctx.lineTo(x + w * 0.1, y - h * 0.45); ctx.stroke(); ctx.shadowBlur = 0; ctx.strokeStyle = INK; ctx.lineWidth = 3.5; windows(2, '#ff9a3a', true); door(); break;
    case 'mushroom': ctx.fillStyle = '#f6e8d8'; rr(ctx, x - w * 0.3, y - h * 0.8, w * 0.6, h * 0.8, 18); ctx.fill(); ctx.stroke(); ctx.fillStyle = base; ctx.beginPath(); ctx.ellipse(x, y - h * 0.78, w * 0.62, h * 0.42, 0, Math.PI, 0); ctx.closePath(); ctx.fill(); ctx.stroke(); for (let i = 0; i < 5; i++) circle(ctx, x - w * 0.4 + i * w * 0.2, y - h * 0.85 - Math.sin(i * 1.3) * 16, 9, '#fff3e6', INK, 2); windows(1, '#9bff8a', true); door(); break;
    case 'coral': for (let i = 0; i < 3; i++) { ctx.strokeStyle = rnd.pick(['#ff9f1c', '#ff6b6b', '#c77dff']); ctx.lineWidth = 16; ctx.beginPath(); ctx.moveTo(x - w / 2 + i * w / 2, y - h * 0.5); ctx.quadraticCurveTo(x - w / 2 + i * w / 2 + 20, y - h * 1.1, x - w / 2 + i * w / 2 - 10, y - h * 1.35); ctx.stroke(); } ctx.strokeStyle = INK; ctx.lineWidth = 3.5; sideFace(side); ctx.fillStyle = base; rr(ctx, x - w / 2, y - h, w, h, 30); ctx.fill(); ctx.stroke(); windows(2, '#7fe0ff', true); door(); for (let i = 0; i < 4; i++) circle(ctx, x - w / 2 + rnd() * w, y - h - rnd() * 40, 5, 'rgba(255,255,255,0.5)', '#fff', 1.5); break;
    case 'adobe': sideFace(side); ctx.fillStyle = base; rr(ctx, x - w / 2, y - h, w, h, 14); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#7a4a14'; for (let i = 0; i < 4; i++) ctx.fillRect(x - w / 2 + 10 + i * (w - 20) / 3, y - h - 8, 10, 22); windows(2, '#3ec7c2'); door(); ctx.fillStyle = '#3ec7c2'; rr(ctx, x - w / 2 - 8, y - h * 0.45, 16, h * 0.45, 6); ctx.fill(); ctx.stroke(); break;
    case 'candy': sideFace(side); ctx.fillStyle = base; rr(ctx, x - w / 2, y - h, w, h, 22); ctx.fill(); ctx.stroke(); ctx.save(); rr(ctx, x - w / 2, y - h, w, h, 22); ctx.clip(); ctx.fillStyle = 'rgba(255,255,255,0.55)'; for (let i = -4; i < 8; i++) { ctx.beginPath(); ctx.moveTo(x - w / 2 + i * 30, y); ctx.lineTo(x - w / 2 + i * 30 + 14, y); ctx.lineTo(x - w / 2 + i * 30 + 14 + h * 0.5, y - h); ctx.lineTo(x - w / 2 + i * 30 + h * 0.5, y - h); ctx.fill(); } ctx.restore(); ctx.stroke(); domeTop(c1, w * 0.55, h * 0.35); circle(ctx, x, y - h - h * 0.35, 12, '#ff4f79', INK); windows(2, '#fff'); door(); break;
    case 'crystal': ctx.fillStyle = rgba(base, 0.9); ctx.beginPath(); ctx.moveTo(x - w / 2, y); ctx.lineTo(x - w / 2 + 8, y - h * 0.7); ctx.lineTo(x - w * 0.15, y - h * 1.35); ctx.lineTo(x + w * 0.2, y - h * 0.85); ctx.lineTo(x + w / 2, y - h * 1.1); ctx.lineTo(x + w / 2 + 4, y); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.fillStyle = 'rgba(255,255,255,0.35)'; ctx.beginPath(); ctx.moveTo(x - w * 0.15, y - h * 1.35); ctx.lineTo(x - w * 0.05, y - h * 0.6); ctx.lineTo(x - w * 0.25, y - h * 0.3); ctx.fill(); windows(2, '#ffffff', true); door(); break;
    case 'neon': sideFace('#0c0c1a'); front('#12122a'); for (let i = 0; i < 4; i++) { ctx.shadowColor = [c0, c1, c2, c0][i]; ctx.shadowBlur = 16; ctx.fillStyle = [c0, c1, c2, c0][i]; ctx.fillRect(x - w / 2 + 6, y - h + 14 + i * (h - 60) / 3, w - 12, 5); } ctx.shadowBlur = 0; windows(3, c1, true); door(); break;
    case 'junk': for (let i = 0; i < 4; i++) { const bw = w * rnd.range(0.5, 1), bh = h * 0.28, bx = x + rnd.range(-w * 0.15, w * 0.15); ctx.fillStyle = rnd.pick(['#a0632b', '#7d7f86', '#5d6068', '#8c5a2b']); ctx.save(); ctx.translate(bx, y - i * bh - bh / 2); ctx.rotate(rnd.range(-0.06, 0.06)); ctx.fillRect(-bw / 2, -bh / 2, bw, bh); ctx.strokeRect(-bw / 2, -bh / 2, bw, bh); ctx.restore(); } ctx.fillStyle = '#e8c25a'; circle(ctx, x + w * 0.4, y - h * 0.5, 14, '#1a1a1a', INK); windows(2, '#ffd84a', true); door(); break;
    case 'hive': ctx.fillStyle = base; ctx.beginPath(); for (let k = 0; k < 6; k++) { const a = k / 6 * Math.PI * 2 + Math.PI / 6; ctx.lineTo(x + Math.cos(a) * w * 0.58, y - h * 0.55 + Math.sin(a) * h * 0.62); } ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.strokeStyle = rgba('#7a5200', 0.6); ctx.lineWidth = 2; for (let k = 0; k < 8; k++) { ctx.beginPath(); for (let j = 0; j < 6; j++) { const a = j / 6 * Math.PI * 2 + Math.PI / 6; ctx.lineTo(x + (k % 4 - 1.5) * 26 + Math.cos(a) * 12, y - h * 0.9 + Math.floor(k / 4) * 24 + Math.sin(a) * 12); } ctx.closePath(); ctx.stroke(); } ctx.strokeStyle = INK; ctx.lineWidth = 3.5; windows(2, '#ffb000', true); door(); break;
    case 'mansion': sideFace('#120e1e'); front('#2a1f3d'); gable('#1a1428'); windows(3, '#c6ff5a', true); door(); ctx.fillStyle = '#1a1428'; ctx.fillRect(x - w / 2 - 14, y - h * 0.9, 8, h * 0.9); break;
    case 'hut': sideFace(side); front(base); ctx.fillStyle = '#8b6a3a'; ctx.beginPath(); ctx.moveTo(x - w / 2 - 16, y - h); ctx.lineTo(x, y - h - h * 0.6); ctx.lineTo(x + w / 2 + 16, y - h); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.strokeStyle = rgba(INK, 0.4); for (let i = 1; i < 5; i++) { ctx.beginPath(); ctx.moveTo(x - (w / 2 + 16) * (1 - i / 5), y - h - h * 0.6 * i / 5); ctx.lineTo(x + (w / 2 + 16) * (1 - i / 5), y - h - h * 0.6 * i / 5); ctx.stroke(); } ctx.strokeStyle = INK; windows(2, '#ffcc66'); door(); break;
    case 'cheese': ctx.fillStyle = '#ffd24a'; ctx.beginPath(); ctx.moveTo(x - w / 2, y); ctx.lineTo(x + w / 2 + d, y); ctx.lineTo(x + w / 2 + d, y - h * 0.8); ctx.lineTo(x - w / 2, y - h * 1.1); ctx.closePath(); ctx.fill(); ctx.stroke(); for (let i = 0; i < 6; i++) ellipse(ctx, x - w / 2 + rnd() * (w + d), y - rnd() * h * 0.7, rnd.range(6, 16), rnd.range(5, 12), '#c98a00', shade('#c98a00', -0.3), 2); windows(2, '#fff3c4'); door(); break;
    case 'ship': ctx.fillStyle = '#6a4a2a'; ctx.beginPath(); ctx.moveTo(x - w / 2 - 20, y - h * 0.55); ctx.lineTo(x + w / 2 + 20, y - h * 0.55); ctx.lineTo(x + w / 2, y); ctx.lineTo(x - w / 2, y); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.fillStyle = base; ctx.fillRect(x - w * 0.3, y - h, w * 0.6, h * 0.45); ctx.strokeRect(x - w * 0.3, y - h, w * 0.6, h * 0.45); ctx.fillStyle = '#4a3a2a'; ctx.fillRect(x + w * 0.15, y - h * 1.7, 8, h * 0.75); ctx.fillStyle = '#f4f4f4'; ctx.beginPath(); ctx.moveTo(x + w * 0.15 + 8, y - h * 1.65); ctx.lineTo(x + w * 0.15 + 70, y - h * 1.25); ctx.lineTo(x + w * 0.15 + 8, y - h * 1.1); ctx.fill(); ctx.stroke(); for (let i = 0; i < 3; i++) circle(ctx, x - w * 0.35 + i * w * 0.28, y - h * 0.3, 9, '#7fd8ff', INK, 2.5); door(); break;
    case 'casino': sideFace('#0d0818'); front('#1a1030'); for (let i = 0; i < 5; i++) { ctx.fillStyle = ['#ffd700', '#e0115f', '#2bf0ff', '#ffd700', '#e0115f'][i]; ctx.shadowColor = ctx.fillStyle; ctx.shadowBlur = 10; ctx.fillRect(x - w / 2 + 4, y - h + 10 + i * (h - 50) / 4, w - 8, 4); } ctx.shadowBlur = 0; ctx.fillStyle = '#ffd700'; rr(ctx, x - w / 2 - 10, y - h - 30, w + 20, 34, 8); ctx.fill(); ctx.stroke(); for (let i = 0; i < 9; i++) circle(ctx, x - w / 2 - 2 + i * (w + 4) / 8, y - h - 13, 4, i % 2 ? '#fff' : '#e0115f', null); windows(2, '#ffd700', true); door(); break;
    case 'flower': ctx.fillStyle = '#5fb95f'; rr(ctx, x - w * 0.28, y - h * 0.8, w * 0.56, h * 0.8, 14); ctx.fill(); ctx.stroke(); for (let i = 0; i < 7; i++) { const a = i / 7 * Math.PI * 2; ellipse(ctx, x + Math.cos(a) * w * 0.34, y - h * 0.85 + Math.sin(a) * h * 0.3, w * 0.2, h * 0.15, c1, INK, 3, a); } circle(ctx, x, y - h * 0.85, w * 0.18, '#ffe66d', INK); windows(1, '#fff0f5'); door(); break;
    case 'factory': sideFace(side); front(base); ctx.fillStyle = '#5a5a66'; ctx.fillRect(x + w * 0.2, y - h * 1.5, 22, h * 0.5); ctx.strokeRect(x + w * 0.2, y - h * 1.5, 22, h * 0.5); for (let k = 0; k < 3; k++) circle(ctx, x + w * 0.2 + 11 + k * 10, y - h * 1.55 - k * 20, 12 + k * 5, `rgba(200,200,210,${0.6 - k * 0.15})`, null); ctx.fillStyle = '#ff8c00'; for (let i = 0; i < 8; i++) { const a = i / 8 * Math.PI * 2; ctx.fillRect(x - w * 0.3 + Math.cos(a) * 22 - 5, y - h * 0.6 + Math.sin(a) * 22 - 5, 10, 10); } circle(ctx, x - w * 0.3, y - h * 0.6, 18, '#ff8c00', INK); windows(2, '#ffe08a', true); door(); break;
    case 'balloon': ctx.fillStyle = '#8a6a3a'; rr(ctx, x - w / 2, y - h * 0.6, w, h * 0.6, 10); ctx.fill(); ctx.stroke(); ellipse(ctx, x, y - h * 1.35, w * 0.55, h * 0.6, base, INK); ctx.strokeStyle = INK; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(x - w * 0.4, y - h * 0.6); ctx.lineTo(x - w * 0.3, y - h * 0.85); ctx.moveTo(x + w * 0.4, y - h * 0.6); ctx.lineTo(x + w * 0.3, y - h * 0.85); ctx.stroke(); ctx.lineWidth = 3.5; ctx.fillStyle = c1; ctx.beginPath(); ctx.ellipse(x, y - h * 1.35, w * 0.2, h * 0.6, 0, 0, Math.PI * 2); ctx.fill(); door(); break;
    case 'bubble': ellipse(ctx, x, y - h * 0.55, w * 0.55, h * 0.6, rgba('#ffffff', 0.35), 'rgba(255,255,255,0.9)', 4); ellipse(ctx, x - w * 0.25, y - h * 0.85, w * 0.12, h * 0.08, 'rgba(255,255,255,0.8)', null); ctx.strokeStyle = INK; ctx.lineWidth = 3.5; windows(2, '#ffe3fa'); door(); break;
    case 'disco': sideFace('#1a0030'); front('#2a0a4a'); for (let i = 0; i < 5; i++) for (let j = 0; j < 3; j++) { ctx.fillStyle = hsl((i * 50 + j * 100 + (o.t || 0) * 90) % 360, 0.9, 0.55); ctx.fillRect(x - w / 2 + 8 + i * (w - 16) / 5, y - h + 8 + j * 18, (w - 16) / 5 - 4, 14); } circle(ctx, x, y - h - 30, 22, '#dddddd', INK); for (let i = 0; i < 12; i++) { ctx.fillStyle = hsl(i * 30, 0.9, 0.6); ctx.fillRect(x - 20 + (i % 4) * 10, y - h - 46 + Math.floor(i / 4) * 11, 8, 9); } door(); break;
    case 'book': let by = y; for (let i = 0; i < 4; i++) { const bw = w * rnd.range(0.75, 1), bh = h / 4; ctx.fillStyle = rnd.pick(['#a83232', '#3a5a8a', '#4a7a3a', '#8b6b4a']); ctx.fillRect(x - bw / 2, by - bh, bw, bh); ctx.strokeRect(x - bw / 2, by - bh, bw, bh); ctx.fillStyle = '#f0e0c0'; ctx.fillRect(x - bw / 2 + bw * 0.06, by - bh + 4, bw * 0.88, 4); by -= bh; } windows(2, '#fff8e0', true); door(); break;
    case 'goo': ctx.fillStyle = base; ctx.beginPath(); ctx.moveTo(x - w / 2 - 10, y); ctx.quadraticCurveTo(x - w / 2 - 20, y - h * 0.9, x - w * 0.1, y - h * 1.05); ctx.quadraticCurveTo(x + w * 0.3, y - h * 1.25, x + w / 2 + 10, y - h * 0.7); ctx.quadraticCurveTo(x + w / 2 + 20, y - h * 0.2, x + w / 2, y); ctx.closePath(); ctx.fill(); ctx.stroke(); for (let i = 0; i < 3; i++) { ctx.fillStyle = base; ctx.beginPath(); ctx.moveTo(x - w * 0.3 + i * w * 0.3 - 8, y - h * 0.9); ctx.quadraticCurveTo(x - w * 0.3 + i * w * 0.3, y - h * 0.5, x - w * 0.3 + i * w * 0.3 + 8, y - h * 0.9); ctx.fill(); } windows(2, '#e6ffe6'); door(); break;
    case 'pizza': ctx.fillStyle = '#e0a040'; ctx.beginPath(); ctx.moveTo(x, y); ctx.lineTo(x - w / 2 - 10, y - h * 1.1); ctx.lineTo(x + w / 2 + 10, y - h * 1.1); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#c8282a'; ctx.beginPath(); ctx.moveTo(x, y - 24); ctx.lineTo(x - w / 2 + 10, y - h * 1.1 + 22); ctx.lineTo(x + w / 2 - 10, y - h * 1.1 + 22); ctx.closePath(); ctx.fill(); for (let i = 0; i < 4; i++) circle(ctx, x + rnd.range(-w * 0.25, w * 0.25), y - h * rnd.range(0.4, 0.95), 11, '#8a1a1c', shade('#8a1a1c', -0.3), 2); door(); break;
    case 'ring': sideFace(side); front(base); ctx.strokeStyle = '#3ee8ff'; ctx.lineWidth = 8; ctx.shadowColor = '#3ee8ff'; ctx.shadowBlur = 14; ctx.beginPath(); ctx.arc(x, y - h, w * 0.5, Math.PI, 0); ctx.stroke(); ctx.shadowBlur = 0; ctx.strokeStyle = INK; ctx.lineWidth = 3.5; windows(2, '#3ee8ff', true); door(); break;
    case 'void': ctx.save(); ctx.translate(0, -12 + Math.sin((o.t || 0) * 1.5) * 4); sideFace('#12082a'); front('#2b1b4a'); ctx.shadowColor = '#c77dff'; ctx.shadowBlur = 24; ctx.strokeStyle = '#c77dff'; ctx.strokeRect(x - w / 2, y - h, w, h); ctx.shadowBlur = 0; ctx.strokeStyle = INK; windows(2, '#c77dff', true); door(); ctx.restore(); break;
    case 'clock': sideFace(side); front(base); gable('#5a3a8a', 6); circle(ctx, x, y - h * 0.68, w * 0.28, '#fff8dc', INK, 3.5); ctx.strokeStyle = INK; ctx.lineWidth = 4; ctx.beginPath(); ctx.moveTo(x, y - h * 0.68); ctx.lineTo(x, y - h * 0.68 - w * 0.2); ctx.moveTo(x, y - h * 0.68); ctx.lineTo(x + w * 0.16, y - h * 0.68 + 6); ctx.stroke(); ctx.lineWidth = 3.5; door(); break;
    case 'ufo': ellipse(ctx, x, y - h * 0.45, w * 0.7, h * 0.22, '#8a95a5', INK, 3.5); ellipse(ctx, x, y - h * 0.62, w * 0.3, h * 0.28, rgba('#7fffd4', 0.6), INK, 3); for (let i = 0; i < 7; i++) circle(ctx, x - w * 0.55 + i * w * 1.1 / 6, y - h * 0.42, 6, i % 2 ? '#7fffd4' : '#ff5ce6', null); ctx.fillStyle = 'rgba(127,255,212,0.25)'; ctx.beginPath(); ctx.moveTo(x - 20, y - h * 0.35); ctx.lineTo(x + 20, y - h * 0.35); ctx.lineTo(x + 60, y); ctx.lineTo(x - 60, y); ctx.fill(); door(); break;
    default: sideFace(side); front(base); gable(roofC); windows(2); door();
  }
  // sign
  if (o.sign) { const sw = Math.max(w * 0.9, o.sign.length * 13 + 30); ctx.fillStyle = o.signColor || c2 || '#ffd23f'; rr(ctx, x - sw / 2, y - h - 46 - (o.signUp || 0), sw, 34, 10); ctx.fill(); ctx.strokeStyle = INK; ctx.lineWidth = 3.5; ctx.stroke(); label(ctx, o.sign, x, y - h - 29 - (o.signUp || 0), 17, '#fff', INK); }
  if (o.glow) { ctx.save(); ctx.shadowColor = '#ffd23f'; ctx.shadowBlur = 30; ctx.strokeStyle = 'rgba(255,214,63,0.9)'; ctx.lineWidth = 6; ctx.strokeRect(x - w / 2 - 12, y - h * 1.45 - 20, w + 24 + d, h * 1.45 + 22); ctx.restore(); }
  ctx.restore();
}

// ---------- item icons ----------
export function drawIcon(ctx, icon, x, y, s = 40, color = '#ffd23f') {
  ctx.save(); ctx.translate(x, y); ctx.scale(s / 40, s / 40); ctx.lineJoin = 'round'; ctx.strokeStyle = INK; ctx.lineWidth = 3;
  switch (icon) {
    case 'cleat': ctx.fillStyle = color; ctx.beginPath(); ctx.moveTo(-22, 8); ctx.lineTo(-18, -10); ctx.quadraticCurveTo(-4, -22, 8, -8); ctx.lineTo(22, 0); ctx.lineTo(22, 10); ctx.lineTo(-22, 10); ctx.fill(); ctx.stroke(); ctx.fillStyle = INK; for (let i = 0; i < 4; i++) ctx.fillRect(-18 + i * 11, 10, 5, 5); break;
    case 'glove': ctx.fillStyle = color; rr(ctx, -14, -6, 28, 26, 8); ctx.fill(); ctx.stroke(); for (let i = 0; i < 4; i++) { rr(ctx, -14 + i * 7.5, -24, 6, 22, 3); ctx.fill(); ctx.stroke(); } rr(ctx, 12, -8, 8, 16, 4); ctx.fill(); ctx.stroke(); break;
    case 'sleeve': case 'arm': ctx.fillStyle = color; rr(ctx, -10, -22, 20, 44, 10); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#fff'; ctx.fillRect(-10, -6, 20, 5); ctx.fillRect(-10, 4, 20, 5); break;
    case 'visor': ctx.fillStyle = color; rr(ctx, -24, -8, 48, 18, 9); ctx.fill(); ctx.stroke(); ctx.fillStyle = 'rgba(255,255,255,0.5)'; rr(ctx, -18, -5, 16, 6, 3); ctx.fill(); break;
    case 'pads': ctx.fillStyle = color; ctx.beginPath(); ctx.arc(-16, -4, 14, 0, 7); ctx.arc(16, -4, 14, 0, 7); ctx.fill(); ctx.stroke(); rr(ctx, -14, -12, 28, 30, 8); ctx.fill(); ctx.stroke(); break;
    case 'boot': ctx.fillStyle = color; ctx.beginPath(); ctx.moveTo(-14, -22); ctx.lineTo(4, -22); ctx.lineTo(4, 0); ctx.lineTo(22, 6); ctx.lineTo(22, 14); ctx.lineTo(-14, 14); ctx.closePath(); ctx.fill(); ctx.stroke(); break;
    case 'band': ctx.fillStyle = color; rr(ctx, -18, -10, 36, 20, 8); ctx.fill(); ctx.stroke(); ctx.fillStyle = INK; ctx.fillRect(-18, -2, 36, 4); break;
    case 'brace': ctx.fillStyle = color; rr(ctx, -12, -22, 24, 44, 8); ctx.fill(); ctx.stroke(); ctx.strokeStyle = '#fff'; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(-12, -12); ctx.lineTo(12, 12); ctx.moveTo(12, -12); ctx.lineTo(-12, 12); ctx.stroke(); break;
    case 'tank': ctx.fillStyle = color; rr(ctx, -12, -20, 24, 40, 10); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#7fe3a6'; rr(ctx, -8, -4, 16, 20, 4); ctx.fill(); break;
    case 'cup': ctx.fillStyle = color; ctx.beginPath(); ctx.moveTo(-14, -18); ctx.lineTo(14, -18); ctx.lineTo(10, 20); ctx.lineTo(-10, 20); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#fff'; ctx.fillRect(-2, -30, 4, 14); break;
    case 'bun': ctx.fillStyle = color; ctx.beginPath(); ctx.arc(0, 0, 20, Math.PI, 0); ctx.fill(); ctx.stroke(); ctx.fillStyle = shade(color, -0.3); rr(ctx, -20, 0, 40, 10, 3); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#fff'; for (let i = 0; i < 3; i++) ctx.fillRect(-10 + i * 8, -12 + (i % 2) * 5, 3, 3); break;
    case 'bowl': ctx.fillStyle = color; ctx.beginPath(); ctx.arc(0, -4, 22, 0, Math.PI); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#c8282a'; ctx.beginPath(); ctx.ellipse(0, -4, 20, 7, 0, 0, 7); ctx.fill(); ctx.stroke(); break;
    case 'waffle': ctx.fillStyle = color; rr(ctx, -20, -20, 40, 40, 8); ctx.fill(); ctx.stroke(); ctx.fillStyle = shade(color, -0.3); for (let i = 0; i < 3; i++) for (let j = 0; j < 3; j++) ctx.fillRect(-15 + i * 12, -15 + j * 12, 8, 8); break;
    case 'juice': ctx.fillStyle = color; rr(ctx, -12, -20, 24, 40, 5); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#fff'; rr(ctx, -8, -12, 16, 14, 3); ctx.fill(); break;
    case 'pizza': ctx.fillStyle = '#e0a040'; ctx.beginPath(); ctx.moveTo(0, 22); ctx.lineTo(-20, -18); ctx.lineTo(20, -18); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#c8282a'; ctx.beginPath(); ctx.moveTo(0, 12); ctx.lineTo(-14, -12); ctx.lineTo(14, -12); ctx.fill(); for (const [px, py] of [[-4, -6], [5, -2], [0, 4]]) circle(ctx, px, py, 3, '#8a1a1c', null); break;
    case 'cookie': circle(ctx, 0, 0, 20, color, INK); for (const [px, py] of [[-8, -6], [6, -8], [2, 6], [-6, 8], [9, 3]]) circle(ctx, px, py, 3, '#3a2a1a', null); break;
    case 'taco': ctx.fillStyle = color; ctx.beginPath(); ctx.arc(0, 4, 22, Math.PI, 0); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#57e86b'; ctx.fillRect(-16, -4, 32, 6); ctx.fillStyle = '#c8282a'; ctx.fillRect(-12, -10, 24, 6); break;
    case 'play': ctx.fillStyle = '#1e6b36'; rr(ctx, -22, -18, 44, 36, 6); ctx.fill(); ctx.stroke(); ctx.strokeStyle = '#fff'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(-22, 8); ctx.lineTo(22, 8); ctx.stroke(); ctx.strokeStyle = color; ctx.beginPath(); ctx.moveTo(-12, 8); ctx.lineTo(-12, -6); ctx.lineTo(4, -12); ctx.stroke(); circle(ctx, -12, 8, 3, '#fff', null); circle(ctx, 10, 8, 3, '#fff', null); break;
    case 'part': ctx.fillStyle = color; for (let i = 0; i < 8; i++) { const a = i / 8 * Math.PI * 2; ctx.fillRect(Math.cos(a) * 16 - 4, Math.sin(a) * 16 - 4, 8, 8); } circle(ctx, 0, 0, 14, color, INK); circle(ctx, 0, 0, 5, INK, null); break;
    case 'ball': ctx.fillStyle = '#8a4a1e'; ctx.beginPath(); ctx.ellipse(0, 0, 22, 13, -0.5, 0, 7); ctx.fill(); ctx.stroke(); ctx.strokeStyle = '#fff'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(-6, 4); ctx.lineTo(6, -4); ctx.stroke(); for (let i = -1; i <= 1; i++) { ctx.beginPath(); ctx.moveTo(i * 4 - 2, i * -3 + 2); ctx.lineTo(i * 4 + 2, i * -3 - 2); ctx.stroke(); } break;
    case 'coin': circle(ctx, 0, 0, 18, color, shade(color, -0.4), 3); label(ctx, '¢', 0, 1, 20, shade(color, -0.4), 'transparent'); break;
    default: circle(ctx, 0, 0, 18, color, INK);
  }
  ctx.restore();
}
